//! Emit Foundry test contracts that reproduce a Halmos counterexample with
//! concrete inputs.

use std::collections::HashMap;

use crate::halmos::Trace;

/// Description of the contract that defines the `check_*` property Halmos ran on.
pub struct PropertyContext<'a> {
    /// Solidity contract name holding the `check_*` function (e.g. `"Properties"`).
    pub contract_name: &'a str,
    /// Import path the emitted file should use (relative to `test/`),
    /// e.g. `"./Properties.t.sol"`.
    pub import_path: &'a str,
    /// Parameters of the `check_*` function in source order, as `(name, solidity_type)`.
    pub params: &'a [(&'a str, &'a str)],
    /// Literals to pass to `new <contract_name>(...)`. Empty for a default constructor.
    pub constructor_args: &'a [&'a str],
}

/// Build a self-contained Foundry test file that reproduces the counterexample:
///   - instantiates the property contract (which sets up its own state),
///   - decodes each cex input into a Solidity literal of the right type,
///   - calls the property function with the inputs in source order.
///
/// Returns the Solidity source as a string. Caller writes it to disk.
pub fn emit_counterexample(trace: &Trace, ctx: &PropertyContext<'_>) -> String {
    let property = trace.property_name();
    let test_name = format!("Cex_{property}");
    let contract_name = format!("Cex_{property}_Test");
    let ctor_args = ctx.constructor_args.join(", ");

    let by_name: HashMap<&str, &str> = trace
        .inputs
        .iter()
        .map(|i| (i.name.as_str(), i.hex_value.as_str()))
        .collect();

    let mut decls = String::new();
    let mut call_args = Vec::new();
    for (name, sol_type) in ctx.params {
        let value = by_name.get(name).copied().unwrap_or("0x0");
        let literal = solidity_literal(sol_type, value);
        let var = sanitize_identifier(name);
        decls.push_str(&format!("        {sol_type} {var} = {literal};\n"));
        call_args.push(var);
    }
    let call_arg_list = call_args.join(", ");

    let import_line = format!(
        "import {{{c}}} from \"{p}\";",
        c = ctx.contract_name,
        p = ctx.import_path
    );

    format!(
        "// SPDX-License-Identifier: MIT\n\
        // Generated by Vergil. Reproduces a Halmos counterexample for `{property}`.\n\
        pragma solidity ^0.8.20;\n\
        \n\
        import {{Test}} from \"forge-std/Test.sol\";\n\
        {import_line}\n\
        \n\
        contract {contract_name} is Test {{\n\
        \x20\x20\x20\x20{props_ty} internal props;\n\
        \n\
        \x20\x20\x20\x20function setUp() public {{\n\
        \x20\x20\x20\x20\x20\x20\x20\x20props = new {props_ty}({ctor_args});\n\
        \x20\x20\x20\x20}}\n\
        \n\
        \x20\x20\x20\x20function test_{test_name}() public {{\n\
        {decls}\
        \x20\x20\x20\x20\x20\x20\x20\x20props.{property}({call_arg_list});\n\
        \x20\x20\x20\x20}}\n\
        }}\n",
        props_ty = ctx.contract_name,
    )
}

/// Encode a hex string as a Solidity literal of the given type.
fn solidity_literal(sol_type: &str, hex_value: &str) -> String {
    let stripped = hex_value.trim_start_matches("0x").trim_start_matches("0X");
    let lower = stripped.to_lowercase();
    match sol_type {
        "address" => {
            let padded = pad_to(&lower, 40);
            format!("address(bytes20(hex\"{padded}\"))")
        }
        t if t.starts_with("bytes") && t.len() > 5 => {
            let bytes_n: usize = t[5..].parse().unwrap_or(32);
            let padded = pad_to(&lower, bytes_n * 2);
            format!("{t}(hex\"{padded}\")")
        }
        "bool" => {
            let is_zero = u128::from_str_radix(&lower, 16)
                .map(|n| n == 0)
                .unwrap_or(true);
            if is_zero {
                "false".into()
            } else {
                "true".into()
            }
        }
        _ => {
            // Default: integer types
            if lower.is_empty() {
                "0".into()
            } else {
                format!("0x{lower}")
            }
        }
    }
}

fn pad_to(hex: &str, target_len: usize) -> String {
    if hex.len() >= target_len {
        hex[hex.len() - target_len..].to_string()
    } else {
        let pad = target_len - hex.len();
        format!("{}{hex}", "0".repeat(pad))
    }
}

fn sanitize_identifier(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 1);
    let mut first = true;
    for c in name.chars() {
        if first && c.is_ascii_digit() {
            out.push('_');
        }
        if c.is_ascii_alphanumeric() || c == '_' {
            out.push(c);
        } else {
            out.push('_');
        }
        first = false;
    }
    if out.is_empty() {
        "_arg".to_string()
    } else {
        out
    }
}

impl Trace {
    /// Halmos sometimes reports the property as `check_foo(uint256,uint256)`;
    /// strip the signature so the emitter can spell the call site correctly.
    pub(crate) fn property_name(&self) -> &str {
        match self.property.find('(') {
            Some(idx) => &self.property[..idx],
            None => &self.property,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::halmos::{NamedValue, Trace};

    fn allowance_trace() -> Trace {
        Trace {
            property: "check_transferFrom_blocks_unauthorized(address,uint256)".to_string(),
            inputs: vec![
                NamedValue {
                    name: "to".to_string(),
                    hex_value: "0x8000000000000000000000000000000000000000".to_string(),
                },
                NamedValue {
                    name: "amount".to_string(),
                    hex_value: "0x80000000000000000000".to_string(),
                },
            ],
            storage_writes: Vec::new(),
        }
    }

    fn ctx<'a>() -> PropertyContext<'a> {
        PropertyContext {
            contract_name: "Properties",
            import_path: "./Properties.t.sol",
            params: &[("to", "address"), ("amount", "uint256")],
            constructor_args: &[],
        }
    }

    #[test]
    fn emit_contains_imports_setup_and_call() {
        let src = emit_counterexample(&allowance_trace(), &ctx());
        assert!(src.contains("import {Test} from \"forge-std/Test.sol\";"));
        assert!(src.contains("import {Properties} from \"./Properties.t.sol\";"));
        assert!(src.contains("function setUp()"));
        assert!(src.contains("props = new Properties();"));
        assert!(src.contains("function test_Cex_check_transferFrom_blocks_unauthorized()"));
        assert!(
            src.contains("props.check_transferFrom_blocks_unauthorized(to, amount);"),
            "rendered: {src}"
        );
    }

    #[test]
    fn emit_orders_args_by_source_signature_not_trace_order() {
        // Swap trace order — emitter must still place `to` first because the
        // PropertyContext lists params as (to, amount).
        let mut t = allowance_trace();
        t.inputs.reverse();
        let src = emit_counterexample(&t, &ctx());
        let to_idx = src.find("address to =").unwrap();
        let amount_idx = src.find("uint256 amount =").unwrap();
        assert!(to_idx < amount_idx, "to must come before amount");
        assert!(src.contains("props.check_transferFrom_blocks_unauthorized(to, amount);"));
    }

    #[test]
    fn address_literal_uses_bytes20_hex() {
        let src = emit_counterexample(&allowance_trace(), &ctx());
        assert!(
            src.contains(
                "address to = address(bytes20(hex\"8000000000000000000000000000000000000000\"));"
            ),
            "rendered: {src}"
        );
    }

    #[test]
    fn uint_literal_is_raw_hex() {
        let src = emit_counterexample(&allowance_trace(), &ctx());
        assert!(
            src.contains("uint256 amount = 0x80000000000000000000;"),
            "rendered: {src}"
        );
    }

    #[test]
    fn pad_to_pads_short_and_truncates_long() {
        assert_eq!(pad_to("ff", 4), "00ff");
        assert_eq!(pad_to("1234", 2), "34");
        assert_eq!(pad_to("abc", 3), "abc");
    }

    #[test]
    fn sanitize_identifier_rejects_bad_chars() {
        assert_eq!(sanitize_identifier("a"), "a");
        assert_eq!(sanitize_identifier("a-b"), "a_b");
        assert_eq!(sanitize_identifier("0a"), "_0a");
        assert_eq!(sanitize_identifier(""), "_arg");
    }

    #[test]
    fn property_signature_is_stripped() {
        let trace = Trace {
            property: "check_foo(uint256,uint256)".to_string(),
            inputs: Vec::new(),
            storage_writes: Vec::new(),
        };
        assert_eq!(trace.property_name(), "check_foo");
    }
}
