// SPDX-License-Identifier: MIT
// Generated by Vergil. Reproduces a Halmos counterexample for `check_transferFrom_blocks_unauthorized`.
pragma solidity ^0.8.20;

import {Test} from "forge-std/Test.sol";
import {Properties} from "./Properties.t.sol";

contract Cex_check_transferFrom_blocks_unauthorized_Test is Test {
    Properties internal props;

    function setUp() public {
        props = new Properties();
    }

    function test_Cex_check_transferFrom_blocks_unauthorized() public {
        address to = address(bytes20(hex"8000000000000000000000000000000000000000"));
        uint256 amount = 0x80000000000000000000;
        props.check_transferFrom_blocks_unauthorized(to, amount);
    }
}
